version: "3"
services:

  psql:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${POSTGRES_PORT_IN_HOST:-5432}:5432"
    volumes:
      - ./docker:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    restart: always
