create table if not exists "Customer" (
    "ID"                        bigint generated by default as identity
                                primary key,
    "Возраст"                   int not null,
    -- С этим полем оч. большие странности, т.к. таблица читается скорей как таблица клиентов,
    -- а по факту происходит жёсткая связка с программой лояльности и она может быть только одна.
    -- Кажется, что скорей должно быть 3 таблицы: клиенты; справочник с программами лояльности; связующая таблица многие ко многим
    -- Но в задании так, считаю что ID уникально в этой таблице и является PK.
    "Программа_лояльности"      varchar(255) not null
                                check ("Программа_лояльности" in ('Ярко', 'Travel', 'CashBack'))
);

create table if not exists "CustomerProduct" (
    -- Лучше бы иметь ID и в этой таблице,
    -- но как есть, вводить того, чего нет не стал
    "Customer_id"               bigint
                                constraint customer_product_customer_id_to_customer_id
                                references "Customer"
                                deferrable initially deferred,
    -- Следующий столбец стоило бы вынести в справочник,
    -- но из задания не понятно бага это или фича, поэтому ограничился проверкой IN
    "Тип_Продукта"              varchar(255) not null
                                check ("Тип_Продукта" in ('Потреб', 'Дебетовая карта', 'Кредитная карта', 'Ипотека', 'Вклад')),
    "Дата начала действия"      date not null,
    "Дата окончания действия"   date not null,
    current_is_active           boolean default false not null
);

create table if not exists "Card" (
    "ID"                        bigint generated by default as identity
                                primary key,
    "Customer_id"               bigint
                                constraint card_customer_id_to_customer_id
                                references "Customer"
                                deferrable initially deferred,
    "тип_карты"                 varchar(255) not null,
    dfrom                       date not null,
    dto                         date not null
);

create table if not exists "Customer_KGD" (
    -- Лучше бы иметь ID и в этой таблице,
    -- но как есть, вводить того, чего нет не стал
    "Customer_id"               bigint
                                constraint customer_kgd_customer_id_to_customer_id
                                references "Customer"
                                deferrable initially deferred,
    -- Плохо описанное поле, т.к. дальше в задании есть отсылки к регионам поэтому решил,
    -- что поле содержит данные и отделения и региона в таком формате «{branch_id} - {region_title}», где
    -- branch_id - номер отделения
    -- region_title - название региона
    "Отделение"                 varchar(255) not null
);

create table if not exists "Transaction" (
    -- Лучше бы иметь ID и в этой таблице,
    -- но как есть, вводить того, чего нет не стал
    -- Поле «дата» решено всё же сделать не датой, как в таблицах выше,
    -- а всё же с более точной временной меткой, хоть это и не описано в задании
    "дата"                      timestamp not null,
    "сумма"                     double precision not null,
    "ID_карта"                  bigint
                                constraint transaction_card_id_to_card_id
                                references "Card"
                                deferrable initially deferred,
    mcc                         varchar(4) not null,
    "номер терминала"           int not null
);
